prepare files for deploying in railway

diff --git a/task-service/Dockerfile b/task-service/Dockerfile
--- a/task-service/Dockerfile
+++ b/task-service/Dockerfile
@@ -1,29 +1,3 @@
-FROM maven:3.9-eclipse-temurin-17 AS build
-WORKDIR /app
-COPY pom.xml .
-RUN mvn dependency:go-offline -B
-COPY src ./src
-RUN mvn clean package -DskipTests
-
-FROM eclipse-temurin:17-jre-alpine
-WORKDIR /app
-RUN addgroup -S spring && adduser -S spring -G spring
-USER spring:spring
-COPY --from=build /app/target/*.jar app.jar
-
-# Wait for dependencies script
-COPY --chown=spring:spring wait-for-it.sh /wait-for-it.sh
-RUN chmod +x /wait-for-it.sh
-
-HEALTHCHECK --interval=30s --timeout=3s --start-period=90s \
-  CMD wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1
-
-EXPOSE 8083
-ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "/app/app.jar"]
-
-
-
-#For deploy in failway
 #FROM maven:3.9-eclipse-temurin-17 AS build
 #WORKDIR /app
 #COPY pom.xml .
@@ -37,6 +11,32 @@ ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "/app/app.jar"]
 #USER spring:spring
 #COPY --from=build /app/target/*.jar app.jar
 #
-## Important: Use PORT environment variable
-#EXPOSE ${PORT:-8083}
-#ENTRYPOINT ["sh", "-c", "java -Xmx400m -Xms256m -Dserver.port=${PORT:-8083} -jar /app/app.jar"]
+## Wait for dependencies script
+#COPY --chown=spring:spring wait-for-it.sh /wait-for-it.sh
+#RUN chmod +x /wait-for-it.sh
+#
+#HEALTHCHECK --interval=30s --timeout=3s --start-period=90s \
+#  CMD wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1
+#
+#EXPOSE 8083
+#ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-jar", "/app/app.jar"]
+
+
+
+#For deploy in failway
+FROM maven:3.9-eclipse-temurin-17 AS build
+WORKDIR /app
+COPY pom.xml .
+RUN mvn dependency:go-offline -B
+COPY src ./src
+RUN mvn clean package -DskipTests
+
+FROM eclipse-temurin:17-jre-alpine
+WORKDIR /app
+RUN addgroup -S spring && adduser -S spring -G spring
+USER spring:spring
+COPY --from=build /app/target/*.jar app.jar
+
+# Important: Use PORT environment variable
+EXPOSE ${PORT:-8083}
+ENTRYPOINT ["sh", "-c", "java -Xmx400m -Xms256m -Dserver.port=${PORT:-8083} -jar /app/app.jar"]
